# Noctalia Theme for Mango
# Generated automatically by Noctalia

shadowscolor = 0x475258ff
rootcolor = 0x232a2eff
bordercolor = 0x7a8478ff
dropcolor = 0xa7c08080
splitcolor = 0x9da9a0ff
focuscolor = 0xa7c080ff
maximizescreencolor = 0xd3c6aaff
urgentcolor = 0xe67e80ff
scratchpadcolor = 0x9da9a0ff
globalcolor = 0x4e6628ff
overlaycolor = 0x90753bff
jump_label_decorate_fg_color = 0x859289ff
jump_label_decorate_bg_color = 0x363f47ff
jump_label_decorate_focus_fg_color = 0x232a2eff
jump_label_decorate_focus_bg_color = 0xa7c080ff
jump_label_decorate_border_color = 0x7a8478ff
group_bar_decorate_fg_color = 0x859289ff
group_bar_decorate_bg_color = 0x363f47ff
group_bar_decorate_focus_fg_color = 0x232a2eff
group_bar_decorate_focus_bg_color = 0xa7c080ff
group_bar_decorate_border_color = 0x7a8478ff
