# Noctalia Theme for Mango
# Generated automatically by Noctalia

shadows_color = 0x475258ff
root_color = 0x232a2eff
border_color = 0x7a8478ff
drop_color = 0xa7c08080
split_color = 0x9da9a0ff
focus_color = 0xa7c080ff
maximized_screen_color = 0xd3c6aaff
urgent_color = 0xe67e80ff
scratchpad_color = 0x9da9a0ff
global_color = 0x4e6628ff
overlay_color = 0x90753bff
jump_label_decorate_fg_color = 0x859289ff
jump_label_decorate_bg_color = 0x363f47ff
jump_label_decorate_focus_fg_color = 0x232a2eff
jump_label_decorate_focus_bg_color = 0xa7c080ff
jump_label_decorate_border_color = 0x7a8478ff
group_bar_decorate_fg_color = 0x859289ff
group_bar_decorate_bg_color = 0x363f47ff
group_bar_decorate_focus_fg_color = 0x232a2eff
group_bar_decorate_focus_bg_color = 0xa7c080ff
group_bar_decorate_border_color = 0x7a8478ff
